### PR TITLE
Sivan

### PR DESCRIPTION
**Pull request by vansi42**
That's the first draft of the homepage. No functionality.

### CODE REVIEW

**Comment by vansi42** [comment]
image

**Review by theborgh — COMMENTED** [review]
Nice work!
Do you think it would it be better to use class-based CSS selectors on the nav and form, for improved flexibility and to avoid future conflicts?
We did not discuss this, but I also wonder whether we should name classes using the BEM (Block-Element-Modifier) system, for clarity and to make life easier if we decide switch to SASS later

**Comment by vansi42** [comment]
@theborgh Yep, I'm working on it! Will add classes to everything and fix it.

**Comment by Noahliberty** [comment]
I have no idea about this stuff guys so I'm okay with whatever you think

**Comment by vansi42** [comment]
@theborgh Hi man, good luck today!! I changed the names to be BEM + used formatter :)

**Review by theborgh — APPROVED** [review]
Looks good to me! :)

**Pull request merged**
